#!/bin/bash

echo "🚀 Deploying Football Squares Testing Portal"
echo "============================================"
echo ""
echo "📧 Email confirmed: btcinfo@protonmail.com"
echo ""
echo "🔧 Starting deployment..."
echo ""

# Check if testing file exists
if [ -f "pages/testing/index.html" ]; then
    echo "✅ Testing portal file found"
else
    echo "❌ Error: Testing portal file not found!"
    exit 1
fi

echo ""
echo "📋 Deployment Instructions:"
echo "==========================="
echo ""
echo "1. Start Next.js server (if not running):"
echo "   pnpm run dev"
echo ""
echo "2. In another terminal, start bore tunnel:"
echo "   ./bore local 3001 --to bore.pub --port 1143"
echo ""
echo "3. Access your testing portal at:"
echo "   🔗 http://bore.pub:1143/testing/"
echo ""
echo "4. Share with testers:"
echo ""
echo "------- COPY MESSAGE BELOW -------"
echo ""
echo "🏈 Football Squares Beta Testing Portal"
echo ""
echo "Please help test our platform:"
echo "🔗 bore.pub:1143/testing/"
echo ""
echo "Testing categories available:"
echo "• Weekly Board Play (35 questions)"
echo "• Season-Long Features (24 questions)"
echo "• Community Board Leader (25 questions)"
echo "• Signature & NFT Art (30 questions)"
echo "• AI Assistant (20 questions)"
echo "• Points & Rewards (23 questions)"
echo ""
echo "Time: ~30 minutes"
echo "Feedback emails to: btcinfo@protonmail.com"
echo ""
echo "Thank you for your help!"
echo ""
echo "------- END MESSAGE -------"
echo ""
echo "✅ Testing portal ready for deployment!"